export const constant = {
  ADMIN: "Admin",
  CUSTOMER: "Customer",
  VENDOR: "Vendor",
  SIGNUP: "Sign Up",
  LOGIN: "Log in",
  EMAIL: "Email",
  PASSWORD: "Password",
  NEW_PASSWORD: "New Password",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  MOBILE_NO: "Mobile No",
  DOB: "DOB",
  ROLE: "Role",
  SUBMIT: "Submit",
  CREATE_ACCOUNT: "Create new account",
  FORGOT_PASSWORD: "Forgot Password",
  ACTIVE_ACCOUNT: "Active account",
  BACK: "Back",
};
