export const constant = {
  ADMIN: "Admin",
  CUSTOMER: "Customer",
  VENDOR: "Vendor",
  SIGNUP: "Sign Up",
  LOGIN: "Log in",
  EMAIL: "Email",
  PASSWORD: "Password",
  NEW_PASSWORD: "New Password",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  MOBILE_NO: "Mobile No",
  DOB: "DOB",
  ROLE: "Role",
  SUBMIT: "Submit",
  CREATE_ACCOUNT: "Create new account",
  FORGOT_PASSWORD: "Forgot Password",
  ACTIVE_ACCOUNT: "Active account",
  BACK: "Back",
  VIEW_PROFILE: "View Profile",
  EDIT: "Edit",
  EDIT_PROFILE: "Edit Profile",
  UPDATE_PASSWORD: "Update Password",
  UPDATE: "Update",
  ADD: "Add",
  VIEW_ADDRESS: "View Address",
  ADD_ADDRESS: "Add Address",
  EDIT_ADDRESS: "Edit Address",
  ADDRESS_LINE_1: "Address Line 1",
  ADDRESS_LINE_2: "Address Line 2",
  CITY: "city",
  STATE: "state",
  COUNTRY: "Country",
  PIN_CODE: "Pin Code",
};
